
jwt :
  secret : 'jwt-DEMO-app+designedby@atbforimplementingother*frameworkdoingwith[java]'

server :
  port : 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/JWTDemoDb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql : true
    properties:
      hibernate:
        format_sql: true
        dialect : org.hibernate.dialect.PostgreSQL81Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: never


